import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans relative overflow-hidden`}>

        {/* Global background cube */}
        <video
          autoPlay
          loop
          muted
          playsInline
          className="pointer-events-none fixed inset-0 w-full h-full object-cover -z-10"
        >
          <source src="/videos/cube.mp4" type="video/mp4" />
        </video>

        {children}

      </body> 
    </html>
  );
}
